deleted:    .gitignore 	modified:   pipelight-docker

diff --git a/pipelight/pipelight-docker b/pipelight/pipelight-docker
--- a/pipelight/pipelight-docker
+++ b/pipelight/pipelight-docker
@@ -1,32 +1,24 @@
 #!/bin/bash
 
-command -v docker || { echo "please install docker" ; exit 1 ; }
+command -v docker || { echo "## please install docker" ; exit 1 ; }
 
-command -v ssh || { echo "please install ssh" ; exit 1 ; }
+command -v ssh || { echo "## please install ssh" ; exit 1 ; }
 
-[ -f ~/.ssh/id_rsa.pub ] || { echo "please use ssh-keygen to generate an ssh key" ; exit 1 ; }
-
-#[ -f id_rsa.pub ] || cp ~/.ssh/id_rsa.pub .
+[ -f ~/.ssh/id_rsa.pub ] || { echo "## please use ssh-keygen to generate an ssh key" ; exit 1 ; }
 
 IMAGENAME=pipelight
 
-## if not docker image tagged pipelight exist
-## create image pipelight
+if sudo docker inspect $IMAGENAME 2>&1 | grep -q "No such image" ; then
+	echo "## Couldn't find image $IMAGENAME, will attempt to build"
+	read -p "Press [Enter] key to continue"
+	#wget https://raw.github.com/Thermionix/Dockerfiles/master/pipelight/Dockerfile
+	#wget https://raw.github.com/Thermionix/Dockerfiles/master/pipelight/start
+	sudo docker build -t "$IMAGENAME" .
+fi
 
-#sudo docker inspect $IMAGENAME 2>&1 | grep -q "No such image"
-#if [ $? -eq 0 ];then
-#  echo "#Couldn't find image $IMAGENAME, will attempt to build"
-#  read -p "Press [Enter] key to continue"
-#  curl https://raw.github.com/Thermionix/Dockerfiles/master/pipelight/Dockerfile | docker build -t "$IMAGENAME" -
-#fi
-
-## check pipelight image
+exit 0
 # sudo docker run pipelight echo "checkcheck" | grep "^checkcheck"
 
-cd ~/git/Dockerfiles/pipelight
-sudo docker build -t "$IMAGENAME" .
-
-# rm id_rsa.pub
 
 JOB=$(sudo docker run -d $IMAGENAME "`cat ~/.ssh/id_rsa.pub`")
 
